### ISSUE TITLE
Help wanted! Is your code a distributed version?

### ISSUE THREAD

**Issue by kanseaveg** [Dakingrai/ood-generalization-semantic-boundary-techniques#1]
I want to try fine-tuning your code using a method without deepspeed, but I didn't find any distributed configuration in your code. Does your code support distributed training?

**Comment by Dakingrai** [comment]
Yes, we use deepspeed for distributed training. You can find the deepspeed configuration under configs/train_deepspeed.json.

**Comment by kanseaveg** [comment]
#2 Try to fix out this problem when using distributed deepspeed zero2.

--- 
Additionally, I would like to ask why the epoch is set to 3072, and i want to know approximately at which one will it yield the best results if token preprocessing is used? thank you.
